### ISSUE TITLE
Exported PDF of digital certificate shows technical codes instead of display names

### ISSUE THREAD

**Issue by jkrwdf** [Digitaler-Impfnachweis/covpass-android#68] opened 2021-08-31 19:15 UTC
## Avoid duplicates
* [X] Bug is not mentioned in the [FAQ](https://digitaler-impfnachweis-app.de/faq/)
* [X] Bug is not already reported in another issue

## Technical details

- Device name: Google Pixel 3 XL
- OS version: Android 11
- App version: 1.85.6

## Describe the bug

When I export my digital vaccination certificates to a PDF (new function with the update from today), the fields "Disease or agent targeted", "Vaccine/prophylaxis", "Vaccine medicinal product" and "Vaccine marketing..." shows the technical code numbers (e.g. "1119349007") instead of the human readable display version from the EU Value Sets document (https://ec.europa.eu/health/sites/default/files/ehealth/docs/digital-green-value-sets_en.pdf).

![image](https://user-images.githubusercontent.com/5329491/131562330-17658ffc-9697-46b1-8965-5ae19bd9199c.png)

## Steps to reproduce the issue

Select certificate and execute "EU Ausdruck erstellen" (I use the App in German). 

## Expected behaviour

Show the human readable texts instead of the codes

**Comment by Jo-Achim** [comment] 2021-09-01 13:11
I can confirm.

In addition, the data on the items "Impfarzneimittel" and "Zulassungsinhaber" have slipped somewhere in the lines - if it is not on purpose.

**Comment by jkrwdf** [comment] 2021-09-02 13:20
I tried the same on my iPad, and there it is OK regarding the shown display values (the same issue as described by Jo-Achim however also exists there), so it is indeed a bug in the Android version.

![image](https://user-images.githubusercontent.com/5329491/131850792-34bfb8e4-e358-43ce-843d-fd823e9d5461.png)

**Comment by jleufgen** [comment] 2021-09-06 13:07
Hi, thanks for the Feedback! Will be fixed with the next release. Best regards!

**Closed by jleufgen** 2021-09-06 13:07 UTC
Labels: bug

**Comment by Jo-Achim** [comment] 2021-09-07 07:59
> 
> When I export my digital vaccination certificates to a PDF (new function with the update from today), the fields "Disease or agent targeted", "Vaccine/prophylaxis", "Vaccine medicinal product" and "Vaccine marketing..." shows the technical code numbers (e.g. "1119349007") instead of the human readable display version from the EU Value Sets document (https://ec.europa.eu/health/sites/default/files/ehealth/docs/digital-green-value-sets_en.pdf).

It is fixed under Android with version 1.95.12 (since yesterday).

**Comment by jkrwdf** [comment] 2021-09-07 09:05
@Jo-Achim  My code is fixed, your line wrapping is still meh 🙃
