### ISSUE TITLE
CovPassCheck variant that shows validity end of recovery certificates

### ISSUE THREAD

**Issue by s09bQ5** [Digitaler-Impfnachweis/covpass-android#111] opened 2021-11-20 13:30 UTC
## Avoid duplicates
* [x] This enhancement request has not already been raised before

## Current Implementation
With CovPassCheck it is not possible to distinguish between vaccination and recovery certificates and it is not shown when the certificate expires.

## Suggested Enhancement
Add a mode where it is displayed if a certificate is a recovery certificate and when its validity expires (6 months since first positive PCR test).

## Expected Benefits
From Wednesday on employers in Germany must check if employees entering the office have a valid certificate. To simplify this daily check they may record if the employee has a vaccination or recovery certificate. For recovery certificates the day of expiry must then also be recorded. This is currently not possible with CovPassCheck.

**Comment by JilAuraya** [comment] 2021-11-22 12:58
Hello s09bQ5, thank you for your feedback and we are always keen on hearing your suggestions. 
Unfortunately, we cannot provide this kind of enhancement since the CovPassCheck was designed that way on purpose. After all, we follow strict data privacy rules and therefore do not show the kind of certificate to the person who checks with the app.

**Comment by treysis** [comment] 2021-11-24 11:42
So it's necessary to bring the yellow passport to show proof of vaccination?!

**Comment by timokoenig** [comment] 2021-11-24 19:33
@treysis no that is not true. You still have the proof if the person checks your QR code with the CovPassCheck app. This ticket is about the validity period and not the proof itself.

Showing the date in CovPassCheck would be good in this case but there are other cases where this date should not be visible. The easiest solution is to give the employer the date from the PCR test + 6 month and this can already be done with the CovPass app

**Comment by treysis** [comment] 2021-11-24 19:38
As I understood the devs don't want to show which kind of certificate it is (vaccination/recovered). By showing the validity period this would disclose which kind of certificate it is.

**Comment by timokoenig** [comment] 2021-11-24 19:58
At this point in time the CovPass app shows both certificates in different colors. When scanning the QR code from the overview, it would be very obvious and in case of the recovery certificate the employee could give the date + 6month to the person scanning. And yes there is a view where those colors are not visible but I would say that those employees need to prove what kind of certificate this is. If you don't use the CovPass app the difference would be even more obvious because vaccinated people would have the yellow pass or an EU certificate which states vaccination certificate. For recovered people there is only the EU certificate and this also states that this is a recovery certificate.

**Comment by jleufgen** [comment] 2022-01-07 12:16
@s09bQ5 could we close this ticket or is the topic still relevant?

**Comment by s09bQ5** [comment] 2022-01-09 01:09
I think this is still relevant.
Also the objection mentioned above that displaying the validity end for recovery certificates would reveal that they are recovery certificates is no longer true since vaccination certificates now also have a limited validity.

**Comment by ingowerren** [comment] 2023-12-18 13:35
In 2021, the European Union introduced the digital COVID certificate as an EU-wide recognised proof of vaccination, recovery or negative testing for COVID-19. This regulation expired on 30 June 2023. On a transitional basis, the EU will continue to operate the technical systems to enable cross-border certificate checks until 31 December 2023. The transitional operation will end on that date.
In Germany, the possibility of issuing digital COVID certificates such as vaccination and recovery certificates will therefore be discontinued on 31 December 2023. The CovPass app and the CovPassCheck app will therefore also be discontinued. The CovPass app will be switched to wallet mode, where the stored certificates will be retained.

What does this mean for you?
All functionalities will continue to beavailable until 31 December 2023.

**From 1 January 2024:**

Support for the app will no longer be offered.

- The apps will no longer be available for (re)download in the app store.
- No new functions will be published.
- Further information can also be found in the CovPass app privacy policy.

**Closed by ingowerren** 2023-12-18 13:35 UTC
Labels: enhancement
