### ISSUE TITLE
App Crash by opening camera for import Cert

### ISSUE THREAD

**Issue by CrazyOlli** [Digitaler-Impfnachweis/covpass-android#100] opened 2021-11-09 12:25 UTC
Covpass V 1.12.0 Source Playstore
Device: Samsung Galaxy Z Fold3 5G - SM-F926B/DS
Android 11, Patchlevel October 2021

**After press "Scan QR Code" the App crashes on both screens.** 
Same issue in CovPass Check App.
It happens everytime, i cant import vacation certificates

Its a new Device, can't say if this happend on other softwareversions.

**Comment by jleufgen** [comment] 2021-11-09 12:50
The bug is known, we are currently working on it. Best regards! :)

**Comment by alexcimander** [comment] 2021-11-09 12:51
hey CrazyOlli,

thank you for the report. With the latest versions of the app we are sadly facing scan-issues with flip and fold devices. We are currently working on a solution! 

we kindly ask you to stay patient - there will be a new release very soon. If you could try it once again after the release your feedback would be awesome!

Thank you and have a good one!

**Comment by CrazyOlli** [comment] 2021-11-09 13:04
Thanks for your fast response. I'll give you a feedback after a new version is released.

**Comment by FaKod** [comment] 2021-11-19 10:56
same on Galaxy Z Fold2 5G

**Comment by nullfact0r** [comment] 2021-11-20 11:23
Just came here to say this also happens on the Z Flip 3 :/

**Comment by nullfact0r** [comment] 2021-11-20 12:42
A workaround that worked for me was obtaining an earlier version (1.165.6), scanning the codes and then updating to the latest version via Google Play.

**Comment by CrazyOlli** [comment] 2021-11-24 22:34
With the new 1.23.2 version, the app is still crashing when you open camera for scanning the QR code

**Comment by Ein-Tim** [comment] 2021-12-02 19:23
@jleufgen & @alexcimander 

Is there any fix for this issue in sight? Is this an issue caused by the library used to scan the QR-Code?

**Comment by jleufgen** [comment] 2021-12-03 07:58
@Ein-Tim we are currently working on a solution! Unfortunately we still have scanning problems with the Flip and Fold devices. In one of the next releases this bug will be fixed.

**Comment by botoxparty** [comment] 2021-12-15 08:14
Also have this issue.

Can't believe this was reported a month ago with no fix yet. 

What are we supposed to do in the meantime?

**Comment by Ein-Tim** [comment] 2021-12-15 08:16
@botoxparty 

A workaround would be to use the Corona-Warn-App.

**Comment by botoxparty** [comment] 2021-12-15 08:29
Ok that works! Thanks!

**Comment by pspot2** [comment] 2021-12-23 17:50
Same problem with the same device as the original poster.

CovPass 1.13.3 from Google Play Store
Device: Samsung Galaxy Z Fold3 5G - SM-F926B/DS
Android 11, Patch level November 2021

**Comment by alexcimander** [comment] 2022-01-06 13:19
**UPDATE:** This issue will be solved with the app version 1.16. 1.16 is planned to be released mid-january! 🚧 🏗️

**New behavior:** Flip- and Fold-Devices can scan certificates without crashing. The fix will affect the CovPass and CovPassCheck.

Thank you for your patience and happy new year everyone!

**Comment by FaKod** [comment] 2022-01-18 07:13
after months (!) of a crashing app, when will this be resolved?

**Comment by Ein-Tim** [comment] 2022-01-18 07:26
@FaKod 

Version 2.16 will fix this, see https://github.com/Digitaler-Impfnachweis/covpass-android/discussions/169.

**Comment by pucherd** [comment] 2022-01-19 15:11
Hello @CrazyOlli , the bug should be fixed with our latest 1.16.1 release.

**Comment by pucherd** [comment] 2022-09-15 07:20
Hello, we are closing this bug as it was fixed in version 1.16.1.
Thank you for reporting it.

**Closed by pucherd** 2022-09-15 07:20 UTC
