### ISSUE TITLE
use of NFC for Certificates

### ISSUE THREAD

**Issue by Moritz-Schmidt** [Digitaler-Impfnachweis/covpass-android#136] opened 2021-12-12 11:32 UTC
## Suggested Enhancement

Certificates should not only be available as a QR-Code but also via NFC, this should also be implemented in the CovPasCheck app.

## Expected Benefits

This would have the benefit that checking the certificate will be faster and can bee implemented in automatic Sytems for example automatic entrance gates that only let through someone with a vaild certificate. There would also be the Benefit, that a Smartphone is not needed for checking a certificate, a little Device with a Microcontroller and a NFC reader would be enough. It would also be possible, to have the certificate on a NFC Tag like a Contactless smart card so you don't need to carry a Smartphone or a piece of Paper with you.

**Comment by jleufgen** [comment] 2021-12-14 09:37
[https://github.com/Digitaler-Impfnachweis/covpass-android/issues/65](url)

**Comment by jleufgen** [comment] 2021-12-14 09:38
https://github.com/Digitaler-Impfnachweis/covpass-android/issues/65

**Comment by Ein-Tim** [comment] 2021-12-14 11:17
This seems like a duplicate of #65 and should be closed.

**Comment by oliver-steinbrecher** [comment] 2021-12-14 16:06
Closing this because of duplicate to #65

**Closed by oliver-steinbrecher** 2021-12-14 16:06 UTC
Labels: enhancement
