### ISSUE TITLE
Import from PDF or photo

### ISSUE THREAD

**Issue by 10Meisterbaelle** [Digitaler-Impfnachweis/covpass-android#51] opened 2021-07-23 17:20 UTC
You should be able to import a COVID certificate from a PDF or photo to make it possible to import it directly on device

**Comment by timokoenig** [comment] 2021-07-25 17:54
Duplicate of https://github.com/Digitaler-Impfnachweis/covpass-android/issues/20

**Closed** 2021-07-28 14:48 UTC
