### ISSUE TITLE
CovPassCheck: App asks mistakenly for correcting the system time

### ISSUE THREAD

**Issue by KaypieCode** [Digitaler-Impfnachweis/covpass-android#119] opened 2021-11-29 15:13 UTC
## Technical details

- Device name: Xiaomi Mi 9T Pro
- OS version: Android 11 (MIUI 12.5.1)
- App version: 1.13.2

## Describe the bug

When starting the App, a text appears telling me to correct my system time (Screenshot) while my system time is completely correct: 

![Screenshot_2021-11-29-16-11-33-171_de.rki.covpass.checkapp.jpg](https://user-images.githubusercontent.com/29100375/143892928-6093e63f-66c8-4f7e-a28e-a250387ea01a.jpg)

## Additional context

The app actually seems to recognize the time correctly, because the time is displayed correctly in the "Update checking rules" menu, for example.

**Comment by pucherd** [comment] 2021-11-29 21:46
Hello @KaypieCode,
Thank you for reporting this bug. We will provide a fix in upcoming releases :) 

Related to #97

**Comment by KaypieCode** [comment] 2022-01-08 01:51
@pucherd 

Is there any ETA yet?

**Comment by pucherd** [comment] 2022-01-17 13:22
@KaypieCode we are currently working on a fix which will be available in one of our upcoming releases.

**Comment by RobTho** [comment] 2022-01-20 14:09
Still happen with 1.16.1 (tested on a Pixel 4a)

**Comment by pucherd** [comment] 2022-01-30 14:32
Hello, this bug will be fixed in 1.18.0 version.

**Comment by KaypieCode** [comment] 2022-02-17 22:18
@pucherd Still there in 1.18

**Comment by MikeMcC399** [comment] 2022-02-18 18:14
- Could this issue be closed, since it is a duplicate of #97?

**Comment by MikeMcC399** [comment] 2022-04-11 10:35
@pucherd 

Is there some reason to keep this duplicate issue open? Wouldn't #97 be sufficient for tracking purposes?

**Comment by pucherd** [comment] 2022-04-11 10:46
@MikeMcC399 you are right #97 would be sufficient for tracking. But both tickets are containing valuable discussions so we left them open.

**Comment by pucherd** [comment] 2022-04-14 11:43
Hello @KaypieCode, 1.22 is release

**Comment by MikeMcC399** [comment] 2022-04-14 12:14
CovPassCheck 1.22.0 is showing no date / time error on my device. Since the error was only sporadic this is not a 100% confirmation that the bug is fixed. I suggest to close the issue and re-open if the issue happens again. Hopefully, the bug is fixed.

**Comment by KaypieCode** [comment] 2022-04-14 12:53
No error anymore on my device

**Closed** 2022-04-14 12:53 UTC
Labels: bug
