### ISSUE TITLE
Unable to scan qr code offline

### ISSUE THREAD

**Issue by NotSoImportant** [Digitaler-Impfnachweis/covpass-android#78] opened 2021-09-21 12:19 UTC
## Describe the bug
This is a follow up issue of #39 
Without internet connection covpass app is starting up correctly, I can press the "+" button to add a certificate, camera (permission is asked and) opens, however it won't scan the code **and there is nothing indicating me why**. 

## Expected behaviour
1. Have an error message that tells about missing internet connection 
2. Have an indication the the qr code was recognized (like other qr scanner apps have) 
3. Add to the documentation that an internet connection is at least required once

## Steps to reproduce the issue
1. (Remove app data, delete the app, install the app) 
2. Go to app info &rarr; data usage &rarr; data usage &rarr; disable mobile data access & disable wifi data access
3. Start the app
4. (click through the descriptions) 
5. Click "+"
6. (grant camera permission) 
7. Try to scan a valid vaccination certificate
8. - nothing happens, no error, no indication that it detected a qr code, nothing - 

## Technical details
- Device name: Motorola G4
- OS version: LineageOS 14 / Android 7
- App version: 1.86.0

## Avoid duplicates
* [x] Bug is not mentioned in the [FAQ](https://digitaler-impfnachweis-app.de/faq/)
* [x] Bug is not already reported in another issue

**Comment by Ein-Tim** [comment] 2021-09-21 14:15
@NotSoImportant 

And just to be sure, directly after you enable the internet connection again it works?

**Comment by jleufgen** [comment] 2021-09-21 15:34
It looks like it is related to the QR code reader. This will be fixed in the next sprint.

**Comment by NotSoImportant** [comment] 2021-09-21 16:31
> @NotSoImportant
> 
> And just to be sure, directly after you enable the internet connection again it works?

Exactly

**Comment by pucherd** [comment] 2021-09-22 11:03
@NotSoImportant thank you for reporting this bug. 
Can you please update your CovPass App to the latest version and check the behaviour again?

**Comment by s09bQ5** [comment] 2021-10-03 15:41
I think this is just the zxing library being bad at detecting complex QR codes in less than perfect conditions. I just tried a bunch of QR scanner apps from F-Droid on my vaccination certificate:

zxing-based:
- [Barcode-Scanner](https://f-droid.org/de/packages/com.google.zxing.client.android): as bad as CovPass Check
- [Binary Eye](https://f-droid.org/de/packages/de.markusfisch.android.binaryeye/): as bad as CovPass Check
- [QR & Barcode Scanner](https://f-droid.org/de/packages/com.example.barcodescanner): as bad as CovPass Check
- [QR Scanner (Privacy Friendly)](https://f-droid.org/de/packages/com.secuso.privacyFriendlyCodeScanner): much worse than CovPass Check in low lighting conditions, but better with good lighting
- [SecScanQR](https://f-droid.org/de/packages/de.t_dankworth.secscanqr): as bad as CovPass Check

zbar-based:
- [Obsqr](https://f-droid.org/de/packages/trikita.obsqr): by far the best
- [QRCode & Barcode scanner](https://f-droid.org/de/packages/com.github.andremiras.qrscan): also good, but low frame rate
- [zbarcamdemo](https://f-droid.org/de/packages/com.github.andremiras.zbarcamdemo): didn't detect it at all and there is nothing to configure

**Comment by alexcimander** [comment] 2021-11-26 07:24
Hey everyone  - did you recheck the behavior? Does it work out for you?

**Comment by alexcimander** [comment] 2021-12-06 10:06
Hey everyone - we will start to close tickets due to inactivity 😢 Please let us know if the behavior pops up again 👍

**Closed by alexcimander** 2021-12-06 10:06 UTC
Labels: bug

**Comment by hamsterclassic** [comment] 2022-02-21 16:56
Just discovered this bug and it still exists with 1.18.
- offline device
- installed covpass 1st time 
- tried to scan 
-> error 422, no explanation

**Comment by timokoenig** [comment] 2022-02-21 16:59
@hamsterclassic thanks for reporting the bug. Can you open a new ticket with your discovery?

**Comment by pucherd** [comment] 2022-02-21 17:07
@hamsterclassic are you able to reproduce it with internet connection? Have you modified the time in your phone?
Error 422 indicates that the CWT token is expired.

**Comment by hamsterclassic** [comment] 2022-02-21 17:09
> @hamsterclassic are you able to reproduce it with internet connection? Have you modified the time in your phone? Error 422 indicates that the CWT token is expired.

- device is offline, date and time are correct
